// This file is generated by Slice Machine. Update with care!

import Blockquote from './Blockquote';
import Comparison from './Comparison';
import DribbbleSlider from './DribbbleSlider';
import FigmaFile from './FigmaFile';
import GitHubRepo from './GitHubRepo';
import NeutralData from './NeutralData';
import Quote from './Quote';
import RichText from './RichText';
import StoreButtons from './StoreButtons';

export {
	Blockquote,
	Comparison,
	DribbbleSlider,
	FigmaFile,
	GitHubRepo,
	NeutralData,
	Quote,
	RichText,
	StoreButtons,
};

export const components = {
	blockquote: Blockquote,
	comparison: Comparison,
	dribbble_slider: DribbbleSlider,
	figma_file: FigmaFile,
	git_hub_repo: GitHubRepo,
	neutral_data: NeutralData,
	quote: Quote,
	rich_text: RichText,
	store_buttons: StoreButtons,
};
