// This file is generated by Slice Machine. Update with care!

import Comparison from './Comparison';
import Quote from './Quote';
import RichText from './RichText';

export {
	Comparison,
	Quote,
	RichText,
};

export const components = {
	comparison: Comparison,
	quote: Quote,
	rich_text: RichText,
};
