import { Inter as createInter } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';
import type { FC, ReactNode } from 'react';

const inter = createInter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  readonly children: ReactNode;
};

const RootLayout: FC<RootLayoutProps> = ({ children }) => (
  <html lang="en">
    <body className={inter.className}>{children}</body>
  </html>
);

export default RootLayout;
