export const speaking = [
  {
    name: 'Shipping Products at Lightspeed',
    year: 2023,
    location: "WDX'23 Conference",
    url: 'https://wdx.design/wdx23-conference',
  },
  {
    name: 'How To Break into the UX/UI Design Industry (Panel) at UTS Careers Panel',
    year: 2021,
    location: 'UTS',
    url: 'https://www.linkedin.com/feed/update/urn:li:activity:6848867048190296064/',
  },
  {
    name: 'Xero Roadshow Breakfast Panel Session at Xero',
    year: 2020,
    location: 'ICC Sydney',
    url: 'https://x.com/haydenbleasel/status/1225231600058679296',
  },
  {
    name: 'Using Gatsby Inside of a Digital Agency at Gatsby Arvos',
    year: 2019,
    location: 'Chippendale, Sydney',
    url: 'https://x.com/PooleyAllan/status/1189674966125436928',
  },
  {
    name: 'Branding for Disruptive Startups at Sydney UX/UI Meetup',
    year: 2019,
    location: 'Servian HQ',
    url: 'https://www.meetup.com/en-AU/Sydney-UX-UI-Meetup/events/266629688/',
  },
  {
    name: 'Branding for Disruptive Startups at Sydney Designers',
    year: 2019,
    location: 'General Assembly',
    url: 'https://www.meetup.com/en-AU/sydney-designers/events/266880417/',
  },
  {
    name: 'Branding Startups at UNSW 10x Accelerator',
    year: 2018,
    location: 'UNSW',
    url: '',
  },
  {
    name: 'Learning to unlearn: how to design for disruptive startups at Sydney Designers',
    year: 2018,
    location: 'SafetyCulture',
    url: 'https://www.slideshare.net/slideshow/learning-to-unlearn-how-to-design-for-disruptive-startups/92165864',
  },
  {
    name: 'Design stories behind our iconic startups at Sydney Designers',
    year: 2018,
    location: 'AcademyXi',
    url: 'https://www.meetup.com/en-AU/sydney-designers/events/253805856/',
  },
  {
    name: 'Building Products at UTS Tech Thursdays',
    year: 2017,
    location: 'UTS',
    url: 'https://www.slideshare.net/slideshow/tech-thursdays-building-products/78362851',
  },
  {
    name: 'Product, Growth and Raising Funds at Hatchery Masterclass',
    year: 2017,
    location: 'UTS',
    url: 'https://www.slideshare.net/HaydenBleasel/hatchery-masterclass-with-spaceship',
  },
  {
    name: 'Designing for Growth',
    year: 2017,
    location: 'AcademyXi',
    url: 'https://www.slideshare.net/slideshow/designing-for-growth-academy-xi/78362740',
  },
  {
    name: 'Designing Products for the World’s Biggest Tech Companies at AcademyXi Panel',
    year: 2017,
    location: 'AcademyXi',
    url: '',
  },
  {
    name: 'Talks at Spaceship (Host) at Spaceship x Sydney Designers Meetup',
    year: 2017,
    location: 'Spaceship HQ',
    url: 'https://www.meetup.com/en-AU/sydney-designers/events/240356226/',
  },
  {
    name: 'Spaceship Panel at Lean Startup Sydney',
    year: 2016,
    location: 'Pivotal Labs',
    url: '',
  },
  {
    name: 'UTS Start-up / Entrepreneur Insight Event',
    year: 2016,
    location: 'UTS',
    url: '',
  },
  {
    name: 'Code Quality',
    year: 2016,
    location: 'Coder Academy',
    url: 'https://www.slideshare.net/slideshow/how-to-write-good-quality-code/78362973',
  },
  {
    name: 'STEM Panel',
    year: 2015,
    location: 'UNSW',
    url: '',
  },
  {
    name: 'Scalable front-end architecture with Atomic CSS',
    year: 2015,
    location: 'Coder Academy',
    url: 'https://www.slideshare.net/slideshow/scalable-frontend-architecture-with-bootstrap-3-atomic-css/78362762',
  },
];

export const interviews = [
  {
    name: 'Design Interview with Hayden Bleasel',
    location: 'Lovers Magazine',
    url: 'https://spaces.is/loversmagazine/interviews/hayden-bleasel',
    year: 2024,
  },
  {
    name: 'Diving into the Node.js Website Redesign',
    location: 'Node.js',
    url: 'https://nodejs.org/en/blog/announcements/diving-into-the-nodejs-website-redesign',
    year: 2024,
  },
  {
    name: 'Ducks in a row',
    location: 'Lookahead',
    url: 'https://createsend.com/t/t-995C46D3D8BF87EC2540EF23F30FEDED',
    year: 2023,
  },
  {
    name: 'How to Improve Your UI Design Skills (2023 guide)',
    location: 'Untitled UI',
    url: 'https://www.untitledui.com/blog/ui-design-skills#hayden-bleasel',
    year: 2023,
  },
  {
    name: 'A brief look at the new Corellium',
    location: 'Corellium',
    url: 'https://www.corellium.com/blog/a-brief-look-at-the-new-corellium',
    year: 2023,
  },
  {
    name: 'How Creative Agencies Can Use Analytics to Prove Success on Jellypepper × Mailchimp',
    location: 'Jellypepper',
    url: 'https://jellypepper.com/blog/how-creative-agencies-can-use-analytics-to-prove-su',
    year: 2023,
  },
  {
    name: 'Timberland launches new TimbsTrails immersive digital storytelling experience via R/GA Australia',
    location: 'Campaign Brief',
    url: 'https://campaignbrief.com/timberland-launches-new-timbstrails-immersive-digital-',
    year: 2022,
  },
  {
    name: 'Redesigning ESLint',
    location: 'ESLint',
    url: 'https://eslint.org/blog/2022/08/redesigning-eslint/',
    year: 2022,
  },
  {
    name: 'Balancing the Grind with Hayden Bleasel, Director of Jellypepper',
    location: 'Balance the Grind',
    url: 'https://balancethegrind.co/interviews/hayden-bleasel-director-of-jellypepper/',
    year: 2020,
  },
  {
    name: 'Workflow with Hayden Bleasel, Director of Jellypepper',
    location: 'Balance the Grind',
    url: 'https://balancethegrind.co/workflow/workflow-with-hayden-bleasel-director-of-jel',
    year: 2020,
  },
  {
    name: 'What do you think of the Titles in Tech Industry?',
    location: 'Product Disrupt',
    url: 'https://blog.productdisrupt.com/what-do-you-think-of-the-titles-in-tech-industry',
    year: 2018,
  },
  {
    name: 'Sydney startup Presumi helps job seekers track how employers interact with their resume',
    location: 'Startup Daily',
    url: 'https://www.startupdaily.net/2016/10/sydney-startup-presumi-helps-job-seekers-se',
    year: 2016,
  },
  {
    name: 'Hard slog and serendipity on the path to overnight success',
    location: 'UTS Newsroom',
    url: '/presumi-uts.pdf',
    year: 2016,
  },
  {
    name: 'The Entrepreneur Zone: Presumi',
    location: 'ICC Sydney',
    url: '/presumi-icc.jpeg',
    year: 2016,
  },
];
