name: CI

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun i

      - name: Check
        run: bun check

      - name: Types
        run: bun types

      - name: Test
        run: bun test

      - name: Build
        run: bunx turbo build --filter=haydenbleasel
